"""Add GDPR fields

Revision ID: 76db6f87b65f
Revises: 
Create Date: 2026-07-06 14:41:03.665929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76db6f87b65f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_settings', sa.Column('data_retention_days', sa.Integer(), nullable=True))
    op.add_column('platform_settings', sa.Column('gdpr_strict_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_settings', 'gdpr_strict_mode')
    op.drop_column('platform_settings', 'data_retention_days')
    # ### end Alembic commands ###
