"""add_mailbox_fields

Revision ID: b4f073ea80c8
Revises: 76db6f87b65f
Create Date: 2026-07-10 20:28:22.137142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f073ea80c8'
down_revision: Union[str, Sequence[str], None] = '76db6f87b65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('sync_frequency', sa.String(), nullable=True))
    op.add_column('email_accounts', sa.Column('webhook_status', sa.String(), nullable=True))
    op.add_column('email_accounts', sa.Column('pipeline_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_accounts', 'pipeline_status')
    op.drop_column('email_accounts', 'webhook_status')
    op.drop_column('email_accounts', 'sync_frequency')
    # ### end Alembic commands ###
