"""Add active_provider to ai_settings

Revision ID: bf6966e251f1
Revises: b4f073ea80c8
Create Date: 2026-08-06 14:58:31.761730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf6966e251f1'
down_revision: Union[str, Sequence[str], None] = 'b4f073ea80c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_votes_candidate_id'), table_name='team_votes')
    op.drop_index(op.f('ix_team_votes_id'), table_name='team_votes')
    op.drop_table('team_votes')
    op.drop_index(op.f('ix_nominations_candidate_id'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_id'), table_name='nominations')
    op.drop_index(op.f('ix_nominations_target_position_id'), table_name='nominations')
    op.drop_table('nominations')
    op.drop_index(op.f('ix_webhook_endpoints_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_scheduled_email_tasks_id'), table_name='scheduled_email_tasks')
    op.drop_table('scheduled_email_tasks')
    op.drop_index(op.f('ix_offer_templates_id'), table_name='offer_templates')
    op.drop_table('offer_templates')
    op.drop_index(op.f('ix_approval_steps_candidate_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.add_column('ai_settings', sa.Column('active_provider', sa.String(), nullable=True))
    op.add_column('ai_settings', sa.Column('provider_config', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'positions', ['applied_position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('ai_settings', 'provider_config')
    op.drop_column('ai_settings', 'active_provider')
    op.create_table('approval_steps',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_steps_pkey'))
    )
    op.create_index(op.f('ix_approval_steps_id'), 'approval_steps', ['id'], unique=False)
    op.create_index(op.f('ix_approval_steps_candidate_id'), 'approval_steps', ['candidate_id'], unique=False)
    op.create_table('offer_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_markdown', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('offer_templates_pkey'))
    )
    op.create_index(op.f('ix_offer_templates_id'), 'offer_templates', ['id'], unique=False)
    op.create_table('scheduled_email_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('send_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('scheduled_email_tasks_candidate_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_email_tasks_pkey'))
    )
    op.create_index(op.f('ix_scheduled_email_tasks_id'), 'scheduled_email_tasks', ['id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_advance_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_advance_score_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_advance_stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('auto_reject_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_reject_score_cutoff', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rejection_delay_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejection_email_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_tagging_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('auto_archive_inactive_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_rules_pkey'))
    )
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('subscribed_events', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_endpoints_pkey'))
    )
    op.create_index(op.f('ix_webhook_endpoints_id'), 'webhook_endpoints', ['id'], unique=False)
    op.create_table('nominations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_position_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nominations_pkey'))
    )
    op.create_index(op.f('ix_nominations_target_position_id'), 'nominations', ['target_position_id'], unique=False)
    op.create_index(op.f('ix_nominations_id'), 'nominations', ['id'], unique=False)
    op.create_index(op.f('ix_nominations_candidate_id'), 'nominations', ['candidate_id'], unique=False)
    op.create_table('team_votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('team_votes_pkey'))
    )
    op.create_index(op.f('ix_team_votes_id'), 'team_votes', ['id'], unique=False)
    op.create_index(op.f('ix_team_votes_candidate_id'), 'team_votes', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
