export type Status =
| "Applied"
| "Screening"
| "Interviewing"
| "Offer"
| "Hired"
| "Rejected";

export interface Candidate {
id: string;
name: string;
initials: string;
avatarColor: string;
email: string;
skills: string[];
experience: number;
company: string;
location: string;
status: Status;
owner: string;
updatedAt: string;
tags: string[];
}

export const CANDIDATES: Candidate[] = [
{
id: "1",
name: "Priya Sharma",
initials: "PS",
avatarColor: "bg-violet-100 text-violet-700",
email: "priya.sharma@email.com",
skills: ["React", "TypeScript", "Node.js", "GraphQL", "AWS"],
experience: 6,
company: "Stripe",
location: "San Francisco",
status: "Interviewing",
owner: "Alex Chen",
updatedAt: "2h ago",
tags: ["Senior", "Frontend"],
},
{
id: "2",
name: "Marcus Owens",
initials: "MO",
avatarColor: "bg-sky-100 text-sky-700",
email: "marcus.owens@email.com",
skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "PyTorch"],
experience: 4,
company: "OpenAI",
location: "New York",
status: "Screening",
owner: "Sarah Kim",
updatedAt: "5h ago",
tags: ["ML Engineer"],
},
{
id: "3",
name: "Laura Voss",
initials: "LV",
avatarColor: "bg-pink-100 text-pink-700",
email: "laura.voss@email.com",
skills: ["Product Design", "Figma", "UX Research", "Prototyping"],
experience: 8,
company: "Airbnb",
location: "Berlin",
status: "Offer",
owner: "Alex Chen",
updatedAt: "1d ago",
tags: ["Design Lead", "Remote"],
},
{
id: "4",
name: "Daniel Park",
initials: "DP",
avatarColor: "bg-emerald-100 text-emerald-700",
email: "daniel.park@email.com",
skills: ["Go", "Kubernetes", "AWS", "Docker", "Terraform"],
experience: 5,
company: "HashiCorp",
location: "Austin",
status: "Hired",
owner: "Raj Patel",
updatedAt: "3d ago",
tags: ["DevOps", "Senior"],
},
{
id: "5",
name: "Sofia Reyes",
initials: "SR",
avatarColor: "bg-amber-100 text-amber-700",
email: "sofia.reyes@email.com",
skills: ["Java", "Spring Boot", "Microservices", "Kafka", "PostgreSQL"],
experience: 10,
company: "Netflix",
location: "Los Angeles",
status: "Applied",
owner: "Sarah Kim",
updatedAt: "1h ago",
tags: ["Backend", "Staff Engineer"],
},
{
id: "6",
name: "Tobias Müller",
initials: "TM",
avatarColor: "bg-rose-100 text-rose-700",
email: "tobias.muller@email.com",
skills: ["Rust", "C++", "Systems Programming", "WebAssembly"],
experience: 12,
company: "Mozilla",
location: "Berlin",
status: "Rejected",
owner: "Raj Patel",
updatedAt: "4d ago",
tags: ["Systems", "Principal"],
},
{
id: "7",
name: "Aisha Johnson",
initials: "AJ",
avatarColor: "bg-teal-100 text-teal-700",
email: "aisha.johnson@email.com",
skills: ["Data Science", "R", "Python", "Apache Spark", "Tableau"],
experience: 3,
company: "Palantir",
location: "New York",
status: "Screening",
owner: "Alex Chen",
updatedAt: "6h ago",
tags: ["Data"],
},
{
id: "8",
name: "Liam O'Brien",
initials: "LO",
avatarColor: "bg-indigo-100 text-indigo-700",
email: "liam.obrien@email.com",
skills: ["iOS", "Swift", "SwiftUI", "Objective-C", "Xcode"],
experience: 7,
company: "Apple",
location: "San Francisco",
status: "Interviewing",
owner: "Sarah Kim",
updatedAt: "2d ago",
tags: ["Mobile", "Senior"],
},
{
id: "9",
name: "Mei Tanaka",
initials: "MT",
avatarColor: "bg-fuchsia-100 text-fuchsia-700",
email: "mei.tanaka@email.com",
skills: ["Vue.js", "React", "CSS", "Accessibility", "Performance"],
experience: 4,
company: "Shopify",
location: "Toronto",
status: "Offer",
owner: "Raj Patel",
updatedAt: "12h ago",
tags: ["Frontend", "A11y"],
},
{
id: "10",
name: "Carlos Ruiz",
initials: "CR",
avatarColor: "bg-orange-100 text-orange-700",
email: "carlos.ruiz@email.com",
skills: ["DevOps", "Terraform", "GCP", "CI/CD", "Linux"],
experience: 9,
company: "Spotify",
location: "London",
status: "Hired",
owner: "Alex Chen",
updatedAt: "5d ago",
tags: ["Infrastructure", "Senior"],
},
{
id: "11",
name: "Natasha Brown",
initials: "NB",
avatarColor: "bg-cyan-100 text-cyan-700",
email: "natasha.brown@email.com",
skills: ["Android", "Kotlin", "Jetpack Compose", "Firebase"],
experience: 5,
company: "Google",
location: "Austin",
status: "Screening",
owner: "Raj Patel",
updatedAt: "3h ago",
tags: ["Mobile", "Android"],
},
{
id: "12",
name: "Ethan Wong",
initials: "EW",
avatarColor: "bg-lime-100 text-lime-700",
email: "ethan.wong@email.com",
skills: ["Security", "Penetration Testing", "SIEM", "Zero Trust", "SOC"],
experience: 11,
company: "CrowdStrike",
location: "Toronto",
status: "Interviewing",
owner: "Sarah Kim",
updatedAt: "1d ago",
tags: ["Security", "Lead"],
},
{
id: "13",
name: "Ines Ferreira",
initials: "IF",
avatarColor: "bg-purple-100 text-purple-700",
email: "ines.ferreira@email.com",
skills: ["Marketing", "SEO", "Analytics", "Growth Hacking", "HubSpot"],
experience: 6,
company: "HubSpot",
location: "London",
status: "Applied",
owner: "Alex Chen",
updatedAt: "2h ago",
tags: ["Growth", "Marketing"],
},
{
id: "14",
name: "Ryan Novak",
initials: "RN",
avatarColor: "bg-blue-100 text-blue-700",
email: "ryan.novak@email.com",
skills: ["Scala", "Apache Flink", "Spark", "Data Engineering", "Kafka"],
experience: 8,
company: "Databricks",
location: "San Francisco",
status: "Rejected",
owner: "Sarah Kim",
updatedAt: "6d ago",
tags: ["Data Eng", "Senior"],
},
{
id: "15",
name: "Grace Liu",
initials: "GL",
avatarColor: "bg-red-100 text-red-700",
email: "grace.liu@email.com",
skills: ["Product Management", "Roadmapping", "Agile", "B2B SaaS"],
experience: 7,
company: "Salesforce",
location: "New York",
status: "Screening",
owner: "Raj Patel",
updatedAt: "4h ago",
tags: ["PM", "Senior"],
},
{
id: "16",
name: "Omar Khalil",
initials: "OK",
avatarColor: "bg-yellow-100 text-yellow-700",
email: "omar.khalil@email.com",
skills: ["PHP", "Laravel", "MySQL", "Redis", "Docker"],
experience: 3,
company: "WooCommerce",
location: "Berlin",
status: "Applied",
owner: "Alex Chen",
updatedAt: "1d ago",
tags: ["Backend", "Mid-level"],
},
{
id: "17",
name: "Vera Kozlov",
initials: "VK",
avatarColor: "bg-green-100 text-green-700",
email: "vera.kozlov@email.com",
skills: ["Blockchain", "Solidity", "Web3", "DeFi", "Ethereum"],
experience: 4,
company: "Coinbase",
location: "Austin",
status: "Interviewing",
owner: "Sarah Kim",
updatedAt: "8h ago",
tags: ["Web3", "Smart Contracts"],
},
{
id: "18",
name: "James Hartley",
initials: "JH",
avatarColor: "bg-slate-100 text-slate-700",
email: "james.hartley@email.com",
skills: ["Finance", "SQL", "Tableau", "Excel", "Python"],
experience: 15,
company: "Goldman Sachs",
location: "London",
status: "Offer",
owner: "Raj Patel",
updatedAt: "3d ago",
tags: ["Quant", "Principal"],
},
{
id: "19",
name: "Amara Diallo",
initials: "AD",
avatarColor: "bg-violet-100 text-violet-700",
email: "amara.diallo@email.com",
skills: ["React Native", "Expo", "TypeScript", "Redux", "GraphQL"],
experience: 2,
company: "Meta",
location: "New York",
status: "Screening",
owner: "Alex Chen",
updatedAt: "30m ago",
tags: ["Mobile", "Junior"],
},
{
id: "20",
name: "Felix Braun",
initials: "FB",
avatarColor: "bg-sky-100 text-sky-700",
email: "felix.braun@email.com",
skills: ["SRE", "Prometheus", "Grafana", "Kubernetes", "Go"],
experience: 10,
company: "SAP",
location: "Berlin",
status: "Hired",
owner: "Sarah Kim",
updatedAt: "7h ago",
tags: ["SRE", "Senior"],
},
];

export const ALL_SKILLS = [
"React",
"TypeScript",
"Python",
"Go",
"Node.js",
"AWS",
"Kubernetes",
"Machine Learning",
"Docker",
"GraphQL",
"Swift",
"Kotlin",
"Rust",
"Java",
"Data Science",
"DevOps",
"Security",
"Product Design",
];

export const ALL_LOCATIONS = [
"San Francisco",
"New York",
"Berlin",
"Austin",
"Toronto",
"London",
"Los Angeles",
];

export const ALL_STATUSES: Status[] = [
"Applied",
"Screening",
"Interviewing",
"Offer",
"Hired",
"Rejected",
];

export const ALL_OWNERS = ["Alex Chen", "Sarah Kim", "Raj Patel"];
